// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMUCEu4NKFIuN8f-e9FoKeR_yisHFhllo',
    appId: '1:204700797754:web:fc75e9672515b227c01e03',
    messagingSenderId: '204700797754',
    projectId: 'clashorg-1f113',
    authDomain: 'clashorg-1f113.firebaseapp.com',
    storageBucket: 'clashorg-1f113.appspot.com',
    measurementId: 'G-0CKL7VJDLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASoAVV_gAFnVAK4jjksxi4ruGk_RqfsSE',
    appId: '1:204700797754:android:1038d5144a893a38c01e03',
    messagingSenderId: '204700797754',
    projectId: 'clashorg-1f113',
    storageBucket: 'clashorg-1f113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8Fn8Ti3Tx1H_VrxpE10U_lp1kFekn0I',
    appId: '1:204700797754:ios:db6bbd1adedbea51c01e03',
    messagingSenderId: '204700797754',
    projectId: 'clashorg-1f113',
    storageBucket: 'clashorg-1f113.appspot.com',
    androidClientId: '204700797754-718i4kaegobloodv2a2c408r4ldaq085.apps.googleusercontent.com',
    iosClientId: '204700797754-14eojv7utta6tqkopsptiha3kp4pbkta.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMUCEu4NKFIuN8f-e9FoKeR_yisHFhllo',
    appId: '1:204700797754:web:bed0a2751ae970a0c01e03',
    messagingSenderId: '204700797754',
    projectId: 'clashorg-1f113',
    authDomain: 'clashorg-1f113.firebaseapp.com',
    storageBucket: 'clashorg-1f113.appspot.com',
    measurementId: 'G-MWS1720F57',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8Fn8Ti3Tx1H_VrxpE10U_lp1kFekn0I',
    appId: '1:204700797754:ios:db6bbd1adedbea51c01e03',
    messagingSenderId: '204700797754',
    projectId: 'clashorg-1f113',
    storageBucket: 'clashorg-1f113.appspot.com',
    androidClientId: '204700797754-718i4kaegobloodv2a2c408r4ldaq085.apps.googleusercontent.com',
    iosClientId: '204700797754-14eojv7utta6tqkopsptiha3kp4pbkta.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

}